### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by Tungee** [shspage/illustrator-scripts#3]
Hi Hiroyuki, here is a nice wiki for some Curve /line  intersection readings:
http://pomax.github.io/bezierinfo/
We talked about curve line intersection problems...

Best Regards

**Comment by shspage** [comment]
Hi Tungee, Thank you for your suggestion!
I know that wiki, though I haven't read all part of it.
I think it is one of the most valuable site about bezier curve on the internet.

A problem I have is about partially overlapped paths and almost (not completely) overlapped paths.
![overlap](https://cloud.githubusercontent.com/assets/3269510/21246255/e5fc47ba-c36a-11e6-90ba-deee60ef4e03.png)

It results massive recursion when it applied the technique described in "Curve/curve intersection" section of that wiki.

Recently, just several days ago, I read the source code of [paper.js](https://github.com/paperjs/paper.js).
Because it has a method "Curve.getIntersections".
And I found it has a part which restricts recursions.
(addCurveIntersections in [src/path/Curve.js](https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js))
So I guess it is considering above condition.

Furthermore, it is using an algorithm called bezier clipping.
I had thought this method is unstable in some precise condition.

I'm planning to try porting this method to Illustrator JavaScript, when I have the time.

**Comment by Tungee** [comment]
Hi Hiroyuki,
i saw that paper.js dokumentation also.No i understand theproblem you
mentioned earlier. But isnt this a worst case scenario with the muiple
overlap?!


2016-12-16 0:40 GMT+01:00 Hiroyuki Sato <notifications@github.com>:

**Comment by shspage** [comment]
Hi Tungee,
Yes, those are the standard cases.
If you ignore the worst case, a program can be go into an infinite loop when it happen.
It may be rare case, but you should consider it if its result is fatal.
